### ISSUE TITLE
When running the evaluation code, an error occurs.

### ISSUE THREAD

**Issue by MDK-L** [tianyi-lab/Superfiltering#1]
vicuna
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.29s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [04:44<00:00,  3.56s/it]
koala
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:10<00:00,  1.81s/it]
 14%|███████████████████████▎                                                                                                                                         | 26/180 [02:46<11:59,  4.67s/it]Token indices sequence length is longer than the specified maximum sequence length for this model (1043 > 512). Running this sequence through the model will result in indexing errors
 14%|███████████████████████▎                                                                                                                                    | 26/180 [02:46<16:26,  6.41s/it]
Traceback (most recent call last):
  File "/home/jovyan/Self-Curate/Superfiltering/evaluation/generation/eva_generation.py", line 142, in <module>
    main()
  File "/home/jovyan/Self-Curate/Superfiltering/evaluation/generation/eva_generation.py", line 124, in main
    generate_ids = model.generate(input_ids, max_length=args.max_length)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/generation/utils.py", line 1466, in generate
    self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)
  File "/opt/conda/lib/python3.11/site-packages/transformers/generation/utils.py", line 1186, in _validate_generated_length
    raise ValueError(
ValueError: Input length of input_ids is 1043, but `max_length` is set to 1024. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

**Comment by MingLiiii** [comment]
Thanks for your interest in our work. 
This is because the input length is longer than ```args. max_length```.  You can simply solve this by changing the ```args. max_length``` to 2048 or larger as you needed.
