### ISSUE TITLE
does this project support Chinese datasets selection?

### ISSUE THREAD

**Issue by lihongxiacream** [tianyi-lab/Superfiltering#5]
Can I choose another models,like Chinese GPT2 model, and will the performance be affected?

**Comment by lihongxiacream** [comment]
The IDF score of Chinese GPT2 model is strange and there is much zero in the result

**Comment by MingLiiii** [comment]
I think it is probably caused by my `Exception Handling` module. You can delete the 
```
try:
exception:
```
and then see what bugs do you have.

**Comment by lihongxiacream** [comment]
Thanks!! I solve this problem and have another question. The gpt2_chinese filter out many questions and answers that do not belong to the same language. I think that this kind of data does make the IDF high because the pre-trained model does favor languages with consistent output and questions. 
![20240730-141621](https://github.com/user-attachments/assets/23950f12-d8f9-4257-a765-5c7aabba1c00)

**Comment by lihongxiacream** [comment]
If I want to select chinese dataset, cherry_llm may be a better choice? although it spent a lot of time

**Comment by lihongxiacream** [comment]
The performance of training data selected by GPT2-Chinese is worse than GPT2

**Comment by MingLiiii** [comment]
I guess that is because GPT2-Chinese was originally worse than the GPT2 model.
